[project]
name = "pong"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Zhuravlev3906", email = "zhuravlev3906@yandex.ru" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
pong = "pong:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
